/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Camila_Camera
 */
public class GUIMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuFrame
     */
    public GUIMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSubtitulo2 = new javax.swing.JLabel();
        jlIconeHome = new javax.swing.JLabel();
        jbLoginConsultor = new javax.swing.JButton();
        jbLoginUsuario1 = new javax.swing.JButton();
        jlCadastreSe = new javax.swing.JLabel();
        jbCadastreSe = new javax.swing.JButton();
        jlLogo = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlSubtitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSubtitulo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSubtitulo2.setText("função da crise econômica (LockDown e isolamento horizontal) provocada pela pandemia do Coronavírus (Covid-19)");

        jlIconeHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home128px.png"))); // NOI18N

        jbLoginConsultor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbLoginConsultor.setText("Login do Consultor");
        jbLoginConsultor.setEnabled(false);
        jbLoginConsultor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginConsultorActionPerformed(evt);
            }
        });

        jbLoginUsuario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbLoginUsuario1.setText("Login do Usuário");
        jbLoginUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginUsuario1ActionPerformed(evt);
            }
        });

        jlCadastreSe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlCadastreSe.setText("Ainda não possui uma conta? Então:");

        jbCadastreSe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbCadastreSe.setText("Cadastre-se");
        jbCadastreSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastreSeActionPerformed(evt);
            }
        });

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo128px.png"))); // NOI18N

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlTitulo.setText("LAWYER - Consultoria Jurídica");

        jlSubtitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlSubtitulo1.setText("Plataforma de consultoria jurídica emergencial para pessoas que contraíram dívidas em");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jlSubtitulo1))
                            .addComponent(jSubtitulo2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jlCadastreSe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jbCadastreSe, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbLoginConsultor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLoginUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addGap(43, 43, 43)
                        .addComponent(jlLogo)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlIconeHome)
                        .addGap(451, 451, 451))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jlLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jlTitulo)))
                .addGap(46, 46, 46)
                .addComponent(jlSubtitulo1)
                .addGap(26, 26, 26)
                .addComponent(jSubtitulo2)
                .addGap(52, 52, 52)
                .addComponent(jlIconeHome, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jbLoginUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jbLoginConsultor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jlCadastreSe)
                .addGap(31, 31, 31)
                .addComponent(jbCadastreSe, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLoginUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginUsuario1ActionPerformed
        //Quando o user clica em login, é redirecionado pra tela de perfil
        GUILoginUsuarioFrame guiloginuser = new GUILoginUsuarioFrame();
        guiloginuser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbLoginUsuario1ActionPerformed

    private void jbCadastreSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastreSeActionPerformed
        ////Quando o user clica em cadastre-se, é redirecionado pra tela de pré-cadastro
        GUITelaPreCadastro guicaduser1 = new GUITelaPreCadastro();
        guicaduser1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbCadastreSeActionPerformed

    private void jbLoginConsultorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginConsultorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLoginConsultorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jSubtitulo2;
    private javax.swing.JButton jbCadastreSe;
    private javax.swing.JButton jbLoginConsultor;
    private javax.swing.JButton jbLoginUsuario1;
    private javax.swing.JLabel jlCadastreSe;
    private javax.swing.JLabel jlIconeHome;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlSubtitulo1;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
