/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.CadastroUsuariolllVO;

/**
 *
 * @author Camila_Camera
 */
public class GUITelaCadastroUsuariolllFrame extends javax.swing.JFrame {
    
    //Método para cadastrar usuário no sistema
    public void cadastrarUsuario () {
        try{
            modelo.CadastroUsuariolllVO cad = new CadastroUsuariolllVO();
            cad.setDataEndividamento(jftfDataEndividamento.getText());
            cad.setSituacaoDoUsuario(jtaMotivo.getText());
            cad.setSituacaoDaHabitacao(jrbAluguel.getText());
            cad.setSituacaoDaHabitacao(jrbProprio.getText());
            cad.setSituacaoDaHabitacao(jrb500.getText());
            cad.setSituacaoDaHabitacao(jrb1000.getText());
            cad.setSituacaoDaHabitacao(jrb2000.getText());
            cad.setSituacaoDaHabitacao(jrb5000.getText());
   
            //Chama a classe CadastroUsuariolllServicos em servicos, que fará a inserção dos dados da classe dentro do banco
            servicos.CadastroUsuariolllServicos pcad = servicos.ServicosFactory.getCadastroUsuariolllServicos();
            pcad.cadastrarUsuario(cad);
            JOptionPane.showMessageDialog(null, "Você foi cadastrado(a) com sucesos!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
            
            //Quando o user clica em salvar, é redirecionado pra tela de perfil
            GUIPerfilUsuarioFrame guiperfil = new GUIPerfilUsuarioFrame();
            guiperfil.setVisible(true);
            this.setVisible(false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ops, algo deu errado!" +e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Método para cancelar as ações do usuário, setando-as para nulo
    public void cancelarCadastro() {
            jftfDataEndividamento.setText(null);
            jtaMotivo.setText(null);
            jrbAluguel.setText(null);
            jrbProprio.setText(null);
            jrb500.setText(null);
            jrb1000.setText(null);
            jrb2000.setText(null);
            jrb5000.setText(null);
    }

    /**
     * Creates new form GUITelaCadastrolllFrame
     */
    public GUITelaCadastroUsuariolllFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btHabitacao = new javax.swing.ButtonGroup();
        btDivida = new javax.swing.ButtonGroup();
        jrbAluguel = new javax.swing.JRadioButton();
        jrbProprio = new javax.swing.JRadioButton();
        jlDivida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlSituacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMotivo = new javax.swing.JTextArea();
        jlHabitacao = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jlVoltar = new javax.swing.JLabel();
        jlSalvar = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jftfDataEndividamento = new javax.swing.JFormattedTextField();
        jrb500 = new javax.swing.JRadioButton();
        jrb1000 = new javax.swing.JRadioButton();
        jrb2000 = new javax.swing.JRadioButton();
        jrb5000 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrbAluguel.setText("Aluguel");

        btHabitacao.add(jrbProprio);
        jrbProprio.setText("Próprio");

        jlDivida.setText("Tamanho da Dívida: (aproximadamente)");

        jLabel1.setText("Data Inicial do Endividamento:");

        jlSituacao.setText("Situação do Usuário (Motivo da dívida e consultoria): ");

        jtaMotivo.setColumns(20);
        jtaMotivo.setRows(5);
        jScrollPane1.setViewportView(jtaMotivo);

        jlHabitacao.setText("Situação de Habitação:");

        jbSalvar.setText("Salvar e finalizar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jlVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/voltar.png"))); // NOI18N
        jlVoltar.setText("jLabel2");

        jlSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        jlSalvar.setText("jLabel2");

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo64px.png"))); // NOI18N
        jlLogo.setText("jLabel2");

        try {
            jftfDataEndividamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btDivida.add(jrb500);
        jrb500.setText("Acima de R$500");

        btDivida.add(jrb1000);
        jrb1000.setText("Acima de R$1000");

        btDivida.add(jrb2000);
        jrb2000.setText("Acima de R$2000");

        btDivida.add(jrb5000);
        jrb5000.setText("Acima de R$5000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jlSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSalvar)
                                .addGap(101, 101, 101)
                                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jftfDataEndividamento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jlDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(195, 195, 195))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlHabitacao)
                                        .addComponent(jlSituacao)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(126, 126, 126)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrbAluguel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrbProprio))
                                    .addComponent(jrb500)
                                    .addComponent(jrb1000)
                                    .addComponent(jrb2000)
                                    .addComponent(jrb5000))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jlLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jftfDataEndividamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jlSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlHabitacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAluguel)
                    .addComponent(jrbProprio))
                .addGap(18, 18, 18)
                .addComponent(jlDivida)
                .addGap(18, 18, 18)
                .addComponent(jrb500)
                .addGap(18, 18, 18)
                .addComponent(jrb1000)
                .addGap(18, 18, 18)
                .addComponent(jrb2000)
                .addGap(18, 18, 18)
                .addComponent(jrb5000)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalvar)
                    .addComponent(jlVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbVoltar))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        //Chama o método de cadastrar
        cadastrarUsuario();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        //Chama o método cancelar
        cancelarCadastro();
        
        //Quando o user clica em voltar, é redirecionado pra a tela anterior de cadastro
            GUITelaCadastroUsuariollFrame guicad = new GUITelaCadastroUsuariollFrame();
            guicad.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jbVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariolllFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariolllFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariolllFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariolllFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITelaCadastroUsuariolllFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btDivida;
    private javax.swing.ButtonGroup btHabitacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JFormattedTextField jftfDataEndividamento;
    private javax.swing.JLabel jlDivida;
    private javax.swing.JLabel jlHabitacao;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlSalvar;
    private javax.swing.JLabel jlSituacao;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JRadioButton jrb1000;
    private javax.swing.JRadioButton jrb2000;
    private javax.swing.JRadioButton jrb500;
    private javax.swing.JRadioButton jrb5000;
    private javax.swing.JRadioButton jrbAluguel;
    private javax.swing.JRadioButton jrbProprio;
    private javax.swing.JTextArea jtaMotivo;
    // End of variables declaration//GEN-END:variables
}
