/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.CadastroUsuariollVO;

/**
 *
 * @author Camila_Camera
 */
public class GUITelaCadastroUsuariollFrame extends javax.swing.JFrame {
    
    //Método para cadastrar usuário no sistema
    public void cadastrarUsuario () {
        try{
            modelo.CadastroUsuariollVO cad = new CadastroUsuariollVO();
            cad.setEspecificacaoDeNegocio(jrbMEI.getText());
            cad.setEspecificacaoDeNegocio(jrbTrabalhoInformal.getText());
            cad.setEspecificacaoDeNegocio(jrbMediaEmpresa.getText());
            cad.setEspecificacaoDeNegocio(jrbEmpresaPP.getText());
            cad.setEspecificacaoDeNegocio(jrbCLT.getText());
            
            cad.setRenda(jrbAte1.getText());
            cad.setRenda(jrbAte2.getText());
            cad.setRenda(jrbAte3.getText());
            cad.setRenda(jrbMais3.getText());
            
            cad.setTipoDeRenda(jrbRendaFixa.getText());
            cad.setTipoDeRenda(jrbRendaVariavel.getText());
   
            //Chama a classe CadastroUsuariollServicos em servicos, que fará a inserção dos dados da classe dentro do banco
            servicos.CadastroUsuariollServicos pcad = servicos.ServicosFactory.getCadastroUsuariollServicos();
            pcad.cadastrarUsuario(cad);
            JOptionPane.showMessageDialog(null, "Você foi cadastrado(a) com sucesos!", "Confirmação", JOptionPane.INFORMATION_MESSAGE);
            //Quando o user clica em salvar, é redirecionado pra tela de perfil
            
            //Quando o user clica em Salvar e continuar, é redirecionado pra a próxima tela de cadastro
            GUITelaCadastroUsuariolllFrame guicad = new GUITelaCadastroUsuariolllFrame();
            guicad.setVisible(true);
            this.setVisible(false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Ops, algo deu errado!" +e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Método para cancelar as ações do usuário, setando-as para nulo
    public void cancelarCadastro() {
            jrbAte1.setText(null);
            jrbAte2.setText(null);
            jrbAte3.setText(null);
            jrbCLT.setText(null);
            jrbEmpresaPP.setText(null);
            jrbMEI.setText(null);
            jrbMais3.setText(null);
            jrbMediaEmpresa.setText(null);
            jrbRendaFixa.setText(null);
            jrbRendaVariavel.setText(null);
            jrbTrabalhoInformal.setText(null);
    }        

    /**
     * Creates new form GUITelaCadastroUsuariollFrame
     */
    public GUITelaCadastroUsuariollFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNegocio = new javax.swing.ButtonGroup();
        btTIpoRenda = new javax.swing.ButtonGroup();
        btRenda = new javax.swing.ButtonGroup();
        jlTipodeRenda = new javax.swing.JLabel();
        jrbMais3 = new javax.swing.JRadioButton();
        jrbTrabalhoInformal = new javax.swing.JRadioButton();
        jrbCLT = new javax.swing.JRadioButton();
        jrbMEI = new javax.swing.JRadioButton();
        jrbRendaFixa = new javax.swing.JRadioButton();
        jrbEmpresaPP = new javax.swing.JRadioButton();
        jrbRendaVariavel = new javax.swing.JRadioButton();
        jrbMediaEmpresa = new javax.swing.JRadioButton();
        jrbAte1 = new javax.swing.JRadioButton();
        jlNegocio = new javax.swing.JLabel();
        jrbAte2 = new javax.swing.JRadioButton();
        jlRenda = new javax.swing.JLabel();
        jrbAte3 = new javax.swing.JRadioButton();
        jbSalvar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jlSalvar = new javax.swing.JLabel();
        jlVoltar = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTipodeRenda.setText("Tipo de Renda:");

        btRenda.add(jrbMais3);
        jrbMais3.setText("Mais de 3 salários minímos");

        btNegocio.add(jrbTrabalhoInformal);
        jrbTrabalhoInformal.setText("Trabalho Informal");
        jrbTrabalhoInformal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTrabalhoInformalActionPerformed(evt);
            }
        });

        btNegocio.add(jrbCLT);
        jrbCLT.setText("Trabalhador Formal (CLT)");

        btNegocio.add(jrbMEI);
        jrbMEI.setText("MEI (Micro Empreendedor Individual - Autônomo)");
        jrbMEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMEIActionPerformed(evt);
            }
        });

        btTIpoRenda.add(jrbRendaFixa);
        jrbRendaFixa.setText("Renda Fixa");

        btNegocio.add(jrbEmpresaPP);
        jrbEmpresaPP.setText("Empresa de Pequeno Porte");
        jrbEmpresaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEmpresaPPActionPerformed(evt);
            }
        });

        btTIpoRenda.add(jrbRendaVariavel);
        jrbRendaVariavel.setText("Renda Variável");

        btNegocio.add(jrbMediaEmpresa);
        jrbMediaEmpresa.setText("Média Empresa");

        btRenda.add(jrbAte1);
        jrbAte1.setText("Até 1 salário minímo");
        jrbAte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAte1ActionPerformed(evt);
            }
        });

        jlNegocio.setText("Especificação de Negócio do Usuário:");

        btRenda.add(jrbAte2);
        jrbAte2.setText("Até 2 salários minímos");

        jlRenda.setText("Renda:");

        btRenda.add(jrbAte3);
        jrbAte3.setText("Até 3 salários minímos");

        jbSalvar.setText("Salvar e continuar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jlSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check.png"))); // NOI18N
        jlSalvar.setText("jLabel1");

        jlVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/voltar.png"))); // NOI18N
        jlVoltar.setText("jLabel1");

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo64px.png"))); // NOI18N
        jlLogo.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNegocio)
                            .addComponent(jrbTrabalhoInformal)
                            .addComponent(jrbMEI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbMais3)
                            .addComponent(jrbAte3)
                            .addComponent(jrbAte2)
                            .addComponent(jrbAte1)
                            .addComponent(jlRenda))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbRendaFixa)
                            .addComponent(jlTipodeRenda)
                            .addComponent(jrbRendaVariavel)
                            .addComponent(jrbEmpresaPP)
                            .addComponent(jrbMediaEmpresa)
                            .addComponent(jrbCLT))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jlSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(jlVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jbSalvar)
                                .addGap(115, 115, 115)
                                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)))
                .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jlRenda)
                        .addGap(18, 18, 18)
                        .addComponent(jrbAte1)
                        .addGap(18, 18, 18)
                        .addComponent(jrbAte2)
                        .addGap(18, 18, 18)
                        .addComponent(jrbAte3)
                        .addGap(18, 18, 18)
                        .addComponent(jrbMais3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSalvar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSalvar)
                            .addComponent(jbVoltar))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNegocio)
                            .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jrbTrabalhoInformal)
                        .addGap(18, 18, 18)
                        .addComponent(jrbMEI)
                        .addGap(49, 49, 49)
                        .addComponent(jrbEmpresaPP)
                        .addGap(18, 18, 18)
                        .addComponent(jrbMediaEmpresa)
                        .addGap(18, 18, 18)
                        .addComponent(jrbCLT)
                        .addGap(33, 33, 33)
                        .addComponent(jlTipodeRenda)
                        .addGap(20, 20, 20)
                        .addComponent(jrbRendaFixa)
                        .addGap(18, 18, 18)
                        .addComponent(jrbRendaVariavel)
                        .addGap(0, 75, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbTrabalhoInformalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTrabalhoInformalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTrabalhoInformalActionPerformed

    private void jrbMEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMEIActionPerformed

    private void jrbEmpresaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEmpresaPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEmpresaPPActionPerformed

    private void jrbAte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAte1ActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        //Chama o método cadastrar
        cadastrarUsuario();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        //Chama método cancelar
        cancelarCadastro();
        
        //Quando o user clica em voltar, é redirecionado pra a tela anterior de cadastro
            GUITelaCadastroUsuarioFrame guicad1 = new GUITelaCadastroUsuarioFrame();
            guicad1.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jbVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITelaCadastroUsuariollFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btNegocio;
    private javax.swing.ButtonGroup btRenda;
    private javax.swing.ButtonGroup btTIpoRenda;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlNegocio;
    private javax.swing.JLabel jlRenda;
    private javax.swing.JLabel jlSalvar;
    private javax.swing.JLabel jlTipodeRenda;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JRadioButton jrbAte1;
    private javax.swing.JRadioButton jrbAte2;
    private javax.swing.JRadioButton jrbAte3;
    private javax.swing.JRadioButton jrbCLT;
    private javax.swing.JRadioButton jrbEmpresaPP;
    private javax.swing.JRadioButton jrbMEI;
    private javax.swing.JRadioButton jrbMais3;
    private javax.swing.JRadioButton jrbMediaEmpresa;
    private javax.swing.JRadioButton jrbRendaFixa;
    private javax.swing.JRadioButton jrbRendaVariavel;
    private javax.swing.JRadioButton jrbTrabalhoInformal;
    // End of variables declaration//GEN-END:variables
}
